services:
  mysql:
    image: mysql:8.0
    container_name: sdp2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SDP2_2526_DB_G01
      MYSQL_USER: SDP2-2526-G01
      MYSQL_PASSWORD: SDP_Ding_123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
