jwt:
  expiration: 86400000
  secret: ${JWT_SECRET}

spring:
  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai/
      chat:
        options:
          model: gemini-2.5-flash
  logging:
    level:
      org.springframework.ai: DEBUG
      com.openai: TRACE
      org.springframework.web.client: TRACE

  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


resend:
  api-key: ${RESEND_API_KEY}
  from: ${EMAIL_FROM:delaware suite <no-reply@delaware-suite.com>}