jwt:
    expiration: 86400000
    secret: jouw-geheime-sleutel-minstens-256-bits-lang-voor-hs256

spring:
    application:
        name: backend
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: SDP_Ding_123
        url: jdbc:mysql://vichogent.be:41219/SDP2_2526_DB_G01?serverTimezone=UTC
        username: SDP2-2526-G01
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true

resend:
    api-key: re_DffPj88a_CmibEmhRSuNH7Zs9VEoxKGz8
    from: ${EMAIL_FROM:delaware suite <no-reply@delaware-suite.com>}