spring.application.name=backend

spring.datasource.url=jdbc:mysql://vichogent.be:41219/SDP2_2526_DB_G01?serverTimezone=UTC
spring.datasource.username=SDP2-2526-G01
spring.datasource.password=SDP_Ding_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
jwt.secret=jouw-geheime-sleutel-minstens-256-bits-lang-voor-hs256
jwt.expiration=86400000